include "../external/yara-rules/capabilities/capabilities.yar"
include "../external/yara-rules/crypto/crypto_signatures.yar"
include "../external/yara-rules/packers/packer_compiler_signatures.yar"
include "../external/yara-rules/packers/peid.yar"
include "../external/yara-rules/antidebug_antivm/antidebug_antivm.yar"